---
- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - vagrant
    docker_daemon_options:
      insecure-registries : ["192.168.44.44:8082"]

  tasks:

  - name: Install packages
    package:
      name:
        - pip
        - conntrack
        - bash-completion
        - etcd-client
      state: present
     
  - name: Install kubernetes python package
    pip:
      name: 
      - kubernetes==23.3.0

  - name: Check the minikube status
    command: minikube status
    register: minikube_status
    changed_when: false
    ignore_errors: true

  - name: Start minikube.
    command: minikube start --driver=none --insecure-registry "192.168.44.44:8082"
    when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
    
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install packages
    package:
      name:
        - socat
        - kubectl
      state: present

  - name: Configure kubectl command auto-completion
    lineinfile:
      dest: /root/.bashrc
      line: 'source <(kubectl completion bash)'
      insertafter: EOF

  roles:
    - packages
    - geerlingguy.docker
    - gantsign.minikube

  collections:
    - kubernetes.core
